simulator:
  physics_dt: 1/240
  rendering_dt: 1/240

tasks:
- type: "SingleInferenceTask"
  name: "test"
  scene_asset_path: GRUtopia/assets/scenes/empty.usd
  scene_scale: [0.01, 0.01, 0.01]
  env_num: 5
  offset_size: 30.0
  robots:
  - name: r1
    prim_path: "/World/r1"
    type: "HumanoidRobot"
    position: [5.58, .5, 1.05]
    scale: [1, 1, 1]
    controller_params:
    - name: "move_by_speed"
    sensor_params:
    - name: "camera"
      enable: true
  - name: r2
    prim_path: "/World/r2"
    type: "HumanoidRobot"
    position: [6, -0.77, 1.05]
    scale: [1, 1, 1]
    controller_params:
    - name: "move_by_speed"
    sensor_params:
    - name: "camera"
      enable: true
