simulator:
  physics_dt: 1/240
  rendering_dt: 1/240

tasks:
- type: "SingleInferenceTask"
  name: "test"
  # scene_asset_path: GRUtopia/assets/scenes/empty.usd
  scene_asset_path: GRUtopia/assets/scenes/empty_dark.usd
  # scene_asset_path: GRUtopia/assets/scenes/bush_flat.usd
  scene_scale: [0.01, 0.01, 0.01]
  # scene_scale: [1.0, 1.0, 1.0]
  # scene_scale: [100.0, 100.0, 100.0]

  env_num: 1
  offset_size: 30.0
  robots:
  - name: r1
    prim_path: "/World/r1"
    type: "HumanoidRobot"
    position: [5.58, .5, 1.05]
    scale: [1, 1, 1]
    controller_params:
    - name: "move_by_speed"
    sensor_params:
    - name: "camera"
      enable: true
  - name: r2
    prim_path: "/World/r2"
    type: "HumanoidRobot"
    position: [6, -0.77, 1.05]
    scale: [1, 1, 1]
    controller_params:
    - name: "move_by_speed"
    sensor_params:
    - name: "camera"
      enable: true
  - name: r3
    prim_path: "/World/r3"
    type: "HumanoidRobot"
    position: [7, -1.5, 1.05]
    scale: [1, 1, 1]
    controller_params:
    - name: "move_by_speed"
    sensor_params:
    - name: "camera"
      enable: true
  # TOOO SLOW TO RUN
  # - name: r4
  #   prim_path: "/World/r4"
  #   type: "HumanoidRobot"
  #   position: [8, -2.25, 1.05]
  #   scale: [1, 1, 1]
  #   controller_params:
  #   - name: "move_by_speed"
  #   sensor_params:
  #   - name: "camera"
  #     enable: true
  # - name: r5
  #   prim_path: "/World/r5"
  #   type: "HumanoidRobot"
  #   position: [9, -3, 1.05]
  #   scale: [1, 1, 1]
  #   controller_params:
  #   - name: "move_by_speed"
  #   sensor_params:
  #   - name: "camera"
  #     enable: true
  